from starter_app.models import (
    User,
    Friend,
    UserList,
    CurrencyList,
    Purchase,
    Recommendation,
)  # noqa
from starter_app import app, db
from dotenv import load_dotenv

load_dotenv()


with app.app_context():
    db.drop_all()
    db.create_all()

    seeder = [
        User(
            username="demoperson",
            firstname="demo",
            lastname="user",
            email="demo@example.com",
            password="password",
            cash=1000,
        ),
        User(
            username="demopersontwo",
            firstname="second",
            lastname="person",
            email="second@example.com",
            password="password",
        ),
        User(
            username="moneyuser",
            firstname="money",
            lastname="user",
            password="password",
            email="money@money.com",
            cash=5000,
        ),
        Friend(
            userId=1,
            friendId=2,
        ),
        Friend(userId=1, friendId=3),
        User(
            username="UserTest",
            firstname="TestFirstName",
            lastname="TestLastName",
            password="password",
            email="test@test.com",
            cash=50000,
        ),
        Friend(userId=3, friendId=4),
        Friend(userId=2, friendId=4),
        UserList(userId=1, listName="Watch List"),
        UserList(userId=1, listName="Crypto"),
        UserList(userId=1, listName="Invest?"),
        UserList(userId=2, listName="Watch List"),
        UserList(userId=3, listName="Watch List"),
        UserList(userId=4, listName="Watch List"),
        CurrencyList(listId=1, tickerSymbol="eth"),
        CurrencyList(listId=1, tickerSymbol="xrp"),
        CurrencyList(listId=1, tickerSymbol="ltc"),
        CurrencyList(listId=1, tickerSymbol="usdt"),
        CurrencyList(listId=1, tickerSymbol="bch"),
        CurrencyList(listId=1, tickerSymbol="bsv"),
        CurrencyList(listId=1, tickerSymbol="xmr"),
        CurrencyList(listId=1, tickerSymbol="eos"),
        CurrencyList(listId=2, tickerSymbol="bnb"),
        CurrencyList(listId=2, tickerSymbol="bsv"),
        CurrencyList(listId=2, tickerSymbol="usdt"),
        CurrencyList(listId=2, tickerSymbol="ltc"),
        CurrencyList(listId=2, tickerSymbol="eth"),
        CurrencyList(listId=1, tickerSymbol="trx"),
        CurrencyList(listId=2, tickerSymbol="xmr"),
        CurrencyList(listId=2, tickerSymbol="ada"),
        CurrencyList(listId=2, tickerSymbol="xtz"),
        CurrencyList(listId=1, tickerSymbol="wbtc"),
        CurrencyList(listId=3, tickerSymbol="xtz"),
        CurrencyList(listId=3, tickerSymbol="trx"),
        CurrencyList(listId=3, tickerSymbol="wbtc"),
        CurrencyList(listId=3, tickerSymbol="ltc"),
        CurrencyList(listId=3, tickerSymbol="dot"),
        CurrencyList(listId=3, tickerSymbol="btc"),
        CurrencyList(listId=3, tickerSymbol="ada"),
        CurrencyList(listId=3, tickerSymbol="eth"),
        CurrencyList(listId=3, tickerSymbol="fil"),
        CurrencyList(listId=3, tickerSymbol="vet"),
        CurrencyList(listId=3, tickerSymbol="dai"),
        Recommendation(
            userId=1,
            friendId=2,
            tickerSymbol="dai",
            message="If you havent heard of this, you should try it!",
        ),
        Recommendation(
            userId=1,
            friendId=2,
            tickerSymbol="vet",
            message="I like the symbol name. buy buy buy!",
        ),
        Recommendation(
            userId=1,
            friendId=2,
            tickerSymbol="btc",
            message="The one true king. bitcoin 4 lyfe",
        ),
        Recommendation(userId=1, friendId=2, tickerSymbol="ltc", message="Good stuff"),
        Recommendation(
            userId=1, friendId=2, tickerSymbol="trx", message="Trix are for kids"
        ),
        Recommendation(
            userId=1,
            friendId=2,
            tickerSymbol="xtz",
            message="Yo, check out the candle sticks on this one",
        ),
        Recommendation(
            userId=1,
            friendId=2,
            tickerSymbol="eth",
            message="This might be better then bitcoin...",
        ),
        Recommendation(
            userId=2, friendId=1, tickerSymbol="wbtc", message="give it a shot"
        ),
        Recommendation(userId=2, friendId=1, tickerSymbol="ltc", message="yup"),
        Recommendation(userId=2, friendId=1, tickerSymbol="bnb", message="Great buy"),
        Recommendation(userId=2, friendId=1, tickerSymbol="eth", message="So good"),
        Recommendation(userId=2, friendId=3, tickerSymbol="eth", message="yasssssssss"),
        Recommendation(userId=2, friendId=3, tickerSymbol="wbtc", message=""),
        Recommendation(
            userId=2, friendId=3, tickerSymbol="btc", message="Great price, buy now!"
        ),
        Recommendation(
            userId=2,
            friendId=4,
            tickerSymbol="eth",
            message="everyone gets a reccomendation",
        ),
        Recommendation(userId=2, friendId=4, tickerSymbol="usdt", message="Good stuff"),
        Recommendation(
            userId=2, friendId=4, tickerSymbol="btc", message="Great price buy now"
        ),
        Recommendation(userId=4, friendId=1, tickerSymbol="btc", message="TEST REC"),
    ]

    for seed in seeder:
        db.session.add(seed)
    db.session.commit()

# stretch seeds
# Purchase(userid=1,
#                  purchasePrice=,
#                  purchaseQuantity=),
#         Purchase(userid=1,
#                  purchasePrice=,
#                  purchaseQuantity=),
#         Purchase(userid=1,
#                  purchasePrice=,
#                  purchaseQuantity=),
#         Purchase(userid=1,
#                  purchasePrice=,
#                  purchaseQuantity=),
#         Purchase(userid=1,
#                  purchasePrice=,
#                  purchaseQuantity=),
#         Purchase(userid=1,
#                  purchasePrice=,
#                  purchaseQuantity=),
#         Purchase(userid=1,
#                  purchasePrice=,
#                  purchaseQuantity=),
#         Purchase(userid=1,
#                  purchasePrice=,
#                  purchaseQuantity=),
#         Purchase(userid=1,
#                  purchasePrice=,
#                  purchaseQuantity=),
#         Purchase(userid=1,
#                  purchasePrice=,
#                  purchaseQuantity=),
#         Purchase(userid=1,
#                  purchasePrice=,
#                  purchaseQuantity=),
#         Purchase(userid=1,
#                  purchasePrice=,
#                  purchaseQuantity=),
#         Purchase(userid=1,
#                  purchasePrice=,
#                  purchaseQuantity=),
#         Purchase(userid=1,
#                  purchasePrice=,
#                  purchaseQuantity=),
#         Purchase(userid=1,
#                  purchasePrice=,
#                  purchaseQuantity=),
#         Purchase(userid=1,
#                  purchasePrice=,
#                  purchaseQuantity=),
#         Purchase(userid=1,
#                  purchasePrice=,
#                  purchaseQuantity=),
#         Purchase(userid=1,
#                  purchasePrice=,
#                  purchaseQuantity=),
#         Purchase(userid=1,
#                  purchasePrice=,
#                  purchaseQuantity=),
#         Purchase(userid=1,
#                  purchasePrice=,
#                  purchaseQuantity=),
#         Purchase(userid=1,
#                  purchasePrice=,
#                  purchaseQuantity=),
#         Purchase(userid=1,
#                  purchasePrice=,
#                  purchaseQuantity=),
#         Purchase(userid=1,
#                  purchasePrice=,
#                  purchaseQuantity=),
#         Purchase(userid=1,
#                  purchasePrice=,
#                  purchaseQuantity=),
#         Purchase(userid=1,
#                  purchasePrice=,
#                  purchaseQuantity=),
#         Purchase(userid=1,
#                  purchasePrice=,
#                  purchaseQuantity=),
#         Purchase(userid=1,
#                  purchasePrice=,
#                  purchaseQuantity=),
#         Purchase(userid=1,
#                  purchasePrice=,
#                  purchaseQuantity=),
#         Purchase(userid=1,
#                  purchasePrice=,
#                  purchaseQuantity=),
#         Purchase(userid=1,
#                  purchasePrice=,
#                  purchaseQuantity=),
