from starter_app.models import (
    User,
    Friend,
    UserList,
    CurrencyList,
    Purchase,
    Recommendation,
)
from starter_app import app, db
from dotenv import load_dotenv

load_dotenv()


with app.app_context():
    db.drop_all()
    db.create_all()

    seeder = [
        User(
            username="demoperson",
            firstname="demo",
            lastname="user",
            email="demo@example.com",
            password="password",
            cash=1000,
        ),
        User(
            username="demopersontwo",
            firstname="second",
            lastname="person",
            email="second@example.com",
            password="password",
        ),
        User(
            username="moneyuser",
            firstname="money",
            lastname="user",
            password="password",
            email="money@money.com",
            cash=5000,
        ),
        Friend(
            userId=1,
            friendId=2,
        ),
        Friend(userId=1, friendId=3),
        User(
            username="UserTest",
            firstname="TestFirstName",
            lastname="TestLastName",
            password="password",
            email="test@test.com",
            cash=50000,
        ),
        Friend(userId=3, friendId=4),
        Friend(userId=2, friendId=4),
        UserList(userId=1, listName="Watch List"),
        UserList(userId=1, listName="Crypto"),
        UserList(userId=1, listName="Invest?"),
        UserList(userId=2, listName="Watch List"),
        UserList(userId=3, listName="Watch List"),
        UserList(userId=4, listName="Watch List"),
        CurrencyList(listId=1, tickerSymbol="eth"),
        CurrencyList(listId=1, tickerSymbol="xrp"),
        CurrencyList(listId=1, tickerSymbol="ltc"),
        CurrencyList(listId=1, tickerSymbol="usdt"),
        CurrencyList(listId=1, tickerSymbol="bch"),
        CurrencyList(listId=1, tickerSymbol="bsv"),
        CurrencyList(listId=1, tickerSymbol="xmr"),
        CurrencyList(listId=1, tickerSymbol="eos"),
        CurrencyList(listId=2, tickerSymbol="bnb"),
        CurrencyList(listId=2, tickerSymbol="bsv"),
        CurrencyList(listId=2, tickerSymbol="usdt"),
        CurrencyList(listId=2, tickerSymbol="ltc"),
        CurrencyList(listId=2, tickerSymbol="eth"),
        CurrencyList(listId=1, tickerSymbol="trx"),
        CurrencyList(listId=2, tickerSymbol="xmr"),
        CurrencyList(listId=2, tickerSymbol="ada"),
        CurrencyList(listId=2, tickerSymbol="xtz"),
        CurrencyList(listId=1, tickerSymbol="wbtc"),
        CurrencyList(listId=3, tickerSymbol="xtz"),
        CurrencyList(listId=3, tickerSymbol="trx"),
        CurrencyList(listId=3, tickerSymbol="wbtc"),
        CurrencyList(listId=3, tickerSymbol="ltc"),
        CurrencyList(listId=3, tickerSymbol="dot"),
        CurrencyList(listId=3, tickerSymbol="btc"),
        CurrencyList(listId=3, tickerSymbol="ada"),
        CurrencyList(listId=3, tickerSymbol="eth"),
        CurrencyList(listId=3, tickerSymbol="fil"),
        CurrencyList(listId=3, tickerSymbol="vet"),
        CurrencyList(listId=3, tickerSymbol="dai"),
        Recommendation(
            userId=1,
            friendId=2,
            tickerSymbol="dai",
            message="If you havent heard of this, you should try it!",
        ),
        Recommendation(
            userId=1,
            friendId=2,
            tickerSymbol="vet",
            message="I like the symbol name. buy buy buy!",
        ),
        Recommendation(
            userId=1,
            friendId=2,
            tickerSymbol="btc",
            message="The one true king. bitcoin 4 lyfe",
        ),
        Recommendation(userId=1, friendId=2, tickerSymbol="ltc", message="Good stuff"),
        Recommendation(
            userId=1, friendId=2, tickerSymbol="trx", message="Trix are for kids"
        ),
        Recommendation(
            userId=1,
            friendId=2,
            tickerSymbol="xtz",
            message="Yo, check out the candle sticks on this one",
        ),
        Recommendation(
            userId=1,
            friendId=2,
            tickerSymbol="eth",
            message="This might be better then bitcoin...",
        ),
        Recommendation(
            userId=2, friendId=1, tickerSymbol="wbtc", message="give it a shot"
        ),
        Recommendation(userId=2, friendId=1, tickerSymbol="ltc", message="yup"),
        Recommendation(userId=2, friendId=1, tickerSymbol="bnb", message="Great buy"),
        Recommendation(userId=2, friendId=1, tickerSymbol="eth", message="So good"),
        Recommendation(userId=2, friendId=3, tickerSymbol="eth", message="yasssssssss"),
        Recommendation(userId=2, friendId=3, tickerSymbol="wbtc", message=""),
        Recommendation(
            userId=2, friendId=3, tickerSymbol="btc", message="Great price, buy now!"
        ),
        Recommendation(
            userId=2,
            friendId=4,
            tickerSymbol="eth",
            message="everyone gets a reccomendation",
        ),
        Recommendation(userId=2, friendId=4, tickerSymbol="usdt", message="Good stuff"),
        Recommendation(
            userId=2, friendId=4, tickerSymbol="btc", message="Great price buy now"
        ),
        Recommendation(userId=4, friendId=1, tickerSymbol="btc", message="TEST REC"),
        Purchase(userId=1,
                 purchasePrice=13398.38,
                 purchaseQuantity=1,
                 tickerSymbol="btc"),
        Purchase(userId=2,
                 purchasePrice=13398.38,
                 purchaseQuantity=.5,
                 tickerSymbol="btc"),
        Purchase(userId=3,
                 purchasePrice=13398.38,
                 purchaseQuantity=2,
                 tickerSymbol="btc"),
        Purchase(userId=1,
                 purchasePrice=389.87,
                 purchaseQuantity=2,
                 tickerSymbol="eth"),
        Purchase(userId=2,
                 purchasePrice=389.87,
                 purchaseQuantity=3,
                 tickerSymbol="eth"),
        Purchase(userId=3,
                 purchasePrice=389.87,
                 purchaseQuantity=.28,
                 tickerSymbol="eth"),
        Purchase(userId=1,
                 purchasePrice=.998235,
                 purchaseQuantity=100,
                 tickerSymbol="usdt"),
        Purchase(userId=2,
                 purchasePrice=.998235,
                 purchaseQuantity=190,
                 tickerSymbol="usdt"),
        Purchase(userId=3,
                 purchasePrice=.998235,
                 purchaseQuantity=20,
                 tickerSymbol="usdt"),
        Purchase(userId=1,
                 purchasePrice=11.57,
                 purchaseQuantity=10,
                 tickerSymbol="link"),
        Purchase(userId=2,
                 purchasePrice=11.57,
                 purchaseQuantity=18,
                 tickerSymbol="link"),
        Purchase(userId=3,
                 purchasePrice=11.57,
                 purchaseQuantity=22,
                 tickerSymbol="link"),
        Purchase(userId=1,
                 purchasePrice=30.06,
                 purchaseQuantity=3,
                 tickerSymbol="bnb"),
        Purchase(userId=2,
                 purchasePrice=30.06,
                 purchaseQuantity=100,
                 tickerSymbol="bnb"),
        Purchase(userId=3,
                 purchasePrice=30.06,
                 purchaseQuantity=1,
                 tickerSymbol="bnb"),
        Purchase(userId=1,
                 purchasePrice=4.11,
                 purchaseQuantity=55,
                 tickerSymbol="dot"),
        Purchase(userId=2,
                 purchasePrice=4.11,
                 purchaseQuantity=20,
                 tickerSymbol="dot"),
        Purchase(userId=3,
                 purchasePrice=4.11,
                 purchaseQuantity=10,
                 tickerSymbol="dot"),
        Purchase(userId=1,
                 purchasePrice=0.097337,
                 purchaseQuantity=10000,
                 tickerSymbol="ada"),
        Purchase(userId=2,
                 purchasePrice=0.097337,
                 purchaseQuantity=500,
                 tickerSymbol="ada"),
        Purchase(userId=3,
                 purchasePrice=0.097337,
                 purchaseQuantity=900,
                 tickerSymbol="ada"),
        Purchase(userId=1,
                 purchasePrice=0.02669433,
                 purchaseQuantity=2000,
                 tickerSymbol="trx"),
        Purchase(userId=2,
                 purchasePrice=0.02669433,
                 purchaseQuantity=200,
                 tickerSymbol="trx"),
        Purchase(userId=3,
                 purchasePrice=0.02669433,
                 purchaseQuantity=500,
                 tickerSymbol="trx"),
        Purchase(userId=1,
                 purchasePrice=0.00256924,
                 purchaseQuantity=10000,
                 tickerSymbol="doge"),
        Purchase(userId=2,
                 purchasePrice=0.00256924,
                 purchaseQuantity=20000,
                 tickerSymbol="doge"),
        Purchase(userId=3,
                 purchasePrice=0.00256924,
                 purchaseQuantity=7000,
                 tickerSymbol="doge"),
        Purchase(userId=1,
                 purchasePrice=6.38,
                 purchaseQuantity=20,
                 tickerSymbol="ewt"),
        Purchase(userId=2,
                 purchasePrice=6.38,
                 purchaseQuantity=10,
                 tickerSymbol="ewt"),
        Purchase(userId=3,
                 purchasePrice=6.38,
                 purchaseQuantity=9,
                 tickerSymbol="ewt"),
        Purchase(userId=1,
                 purchasePrice=7.17,
                 purchaseQuantity=28,
                 tickerSymbol="btg"),
        Purchase(userId=2,
                 purchasePrice=7.17,
                 purchaseQuantity=100,
                 tickerSymbol="btg"),
        Purchase(userId=3,
                 purchasePrice=7.17,
                 purchaseQuantity=15.5,
                 tickerSymbol="btg"),
        Purchase(userId=1,
                 purchasePrice=-7.17,
                 purchaseQuantity=-10,
                 tickerSymbol="btg"),
        Purchase(userId=1,
                 purchasePrice=-15000,
                 purchaseQuantity=-1,
                 tickerSymbol="btc"),
        Purchase(userId=1,
                 purchasePrice=13398.38,
                 purchaseQuantity=2,
                 tickerSymbol="btc"),
        Purchase(userId=1,
                 purchasePrice=-11.57,
                 purchaseQuantity=-4,
                 tickerSymbol="link"),
        Purchase(userId=1,
                 purchasePrice=-399.87,
                 purchaseQuantity=-1,
                 tickerSymbol="eth"),
        Purchase(userId=1,
                 purchasePrice=-1.998235,
                 purchaseQuantity=-50,
                 tickerSymbol="usdt"),
        Purchase(userId=1,
                 purchasePrice=-20.06,
                 purchaseQuantity=-3,
                 tickerSymbol="bnb"),
        Purchase(userId=1,
                 purchasePrice=3.14,
                 purchaseQuantity=20,
                 tickerSymbol="ant"),
        Purchase(userId=1,
                 purchasePrice=2.42,
                 purchaseQuantity=15,
                 tickerSymbol="ar"),
        Purchase(userId=1,
                 purchasePrice=10.55,
                 purchaseQuantity=27,
                 tickerSymbol="bal"),
        Purchase(userId=1,
                 purchasePrice=-6,
                 purchaseQuantity=-27,
                 tickerSymbol="bal"),
        Purchase(userId=1,
                 purchasePrice=11592.43,
                 purchaseQuantity=1.2,
                 tickerSymbol="yfi"),
        Purchase(userId=1,
                 purchasePrice=-12080.43,
                 purchaseQuantity=1,
                 tickerSymbol="yfi"),
        Purchase(userId=1,
                 purchasePrice=57.01,
                 purchaseQuantity=5,
                 tickerSymbol="zec"),
        Purchase(userId=1,
                 purchasePrice=0.61452,
                 purchaseQuantity=100,
                 tickerSymbol="theta"),
    ]

    for seed in seeder:
        db.session.add(seed)
    db.session.commit()
